export const OPEN_FORM_MODAL = 'OPEN_FORM_MODAL';
export const CLOSE_FORM_MODAL = 'CLOSE_FORM_MODAL';
export const TOGGLE_FORM_MODAL = 'TOGGLE_FORM_MODAL';

export const FETCH_POSTS_REQUEST = 'FETCH_POSTS_REQUEST';
export const FETCH_POSTS_FAILURE = 'FETCH_POSTS_FAILURE';
export const FETCH_POSTS_SUCCESS = 'FETCH_POSTS_SUCCESS';

export const CREATE_TODO = 'CREATE_TODO';
export const EDIT_TODO = 'EDIT_TODO';
export const STORE_TODO = 'STORE_TODO';
export const UPDATE_TODO = 'UPDATE_TODO';
export const DELETE_TODO = 'DELETE_TODO';
